name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: docker://ros:foxy-ros-base-focal
      
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: ros_ws/src/rmf_core
    - name: setup
      run: |
        cd ros_ws
    - name: build
      uses: ros-tooling/action-ros-ci@v0.1
      with:
        target-ros2-distro: foxy
        # build all packages listed in the meta package
        package-name: |
          rmf_traffic
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ros_ws/lcov/total_coverage.info
        flags: tests
        name: lean_and_mean_codecov_bot
